"""auto update

Revision ID: d69ee6be9ac4
Revises: 
Create Date: 2026-06-20 17:17:20.077125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69ee6be9ac4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=True),
    sa.Column('pi_uid', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributions_id'), 'contributions', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pi_uid', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('data', sa.String(), server_default='{}', nullable=True),
    sa.Column('read', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('pi_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pi_uid', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('reputation', sa.Integer(), server_default='0', nullable=True),
    sa.Column('voting_power', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('pi_locked', sa.Float(), server_default='0', nullable=True),
    sa.Column('streak_days', sa.Integer(), server_default='0', nullable=True),
    sa.Column('kyc_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('language', sa.String(), server_default='fr', nullable=True),
    sa.Column('badges', sa.String(), server_default='[]', nullable=True),
    sa.Column('level', sa.String(), server_default='bronze', nullable=True),
    sa.Column('last_active', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pi_profiles_id'), 'pi_profiles', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('raised', sa.Float(), server_default='0', nullable=True),
    sa.Column('status', sa.String(), server_default='proposed', nullable=True),
    sa.Column('votes_for', sa.Integer(), server_default='0', nullable=True),
    sa.Column('votes_against', sa.Integer(), server_default='0', nullable=True),
    sa.Column('voter_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('milestones', sa.String(), server_default='[]', nullable=True),
    sa.Column('team', sa.String(), server_default='[]', nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('escrow_contract_id', sa.String(), nullable=True),
    sa.Column('quorum', sa.Float(), server_default='0.05', nullable=True),
    sa.Column('threshold', sa.Float(), server_default='0.66', nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('quest_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quest_id', sa.String(), nullable=False),
    sa.Column('pi_uid', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('claimed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_progress_id'), 'quest_progress', ['id'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quest_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quest_type', sa.String(), nullable=False),
    sa.Column('requirement_type', sa.String(), nullable=False),
    sa.Column('requirement_target', sa.Integer(), nullable=False),
    sa.Column('reward_reputation', sa.Integer(), server_default='0', nullable=True),
    sa.Column('reward_pi_amount', sa.Float(), server_default='0', nullable=True),
    sa.Column('reward_badge', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_id'), 'quests', ['id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('pi_uid', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_quests_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_quest_progress_id'), table_name='quest_progress')
    op.drop_table('quest_progress')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_pi_profiles_id'), table_name='pi_profiles')
    op.drop_table('pi_profiles')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_contributions_id'), table_name='contributions')
    op.drop_table('contributions')
    # ### end Alembic commands ###